// <auto-generated />
namespace Bullet_Journal_5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Version3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version3));
        
        string IMigrationMetadata.Id
        {
            get { return "202102191742140_Version3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
